### ISSUE TITLE
html-webpack-plugin: Filename undefined.

### ISSUE THREAD

**Issue by pungggi** [georgberecz/rebuild-changed-entrypoints-webpack-plugin#2]
Hello I am getting Rebuild: No cache entry for undefined
![grafik](https://user-images.githubusercontent.com/5635709/49204248-87e9be00-f3ab-11e8-9c2e-39cc9c1276d3.png)

This is my config:

```js
const HotModuleReplacementPlugin = require("webpack")
  .HotModuleReplacementPlugin;
const RebuildChangedPlugin = require("rebuild-changed-entrypoints-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  entry: "./src/index.js",
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ["babel-loader"]
      }
    ]
  },
  resolve: {
    extensions: ["*", ".js"]
  },
  output: {
    path: __dirname + "/build",
    publicPath: "/",
    filename: "[name][hash].js"
  },
  plugins: [
    new HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      hash: true,
      template: "./src/index.html",
      filename: "./index.html"
    }),
    new RebuildChangedPlugin({
      cacheDirectory: __dirname,
      logLevel: "debug"
    })
  ],
  devServer: {
    contentBase: "./build",
    hot: true
  }
};
`

**Comment by pungggi** [comment]
It might be related to https://github.com/jantimon/html-webpack-plugin/issues/895#issuecomment-373718299

Edit: this is also an issue, but comes from the said plugin. in this case the plugin does not provide a filename for html entries. not a big issue at the moment though.

**Comment by pungggi** [comment]
by the way I am on windows..
![grafik](https://user-images.githubusercontent.com/5635709/49207811-50ccda00-f3b6-11e8-8c48-91dd6877a87f.png)

**Comment by pungggi** [comment]
Found the reason.. Will do a PR.. 
https://github.com/georgberecz/rebuild-changed-entrypoints-webpack-plugin/pull/3

**Comment by georgberecz** [comment]
Hey @pungggi ,
sorry for the late response. Thanks for creating an issue. I will look into your PR tomorrow. :)
Best, Georg

**Comment by pungggi** [comment]
Hi @georgberecz thank you it has no priority anymore.
